name: Manifests

# Detect if the PR introduced changes to image definitions / manifests and post
# a comment on the PR

# NOTE: Restricting branches prevents jobs from being doubled since a push to a
# pull request triggers two events.
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  check-manifests:
    name: "Check manifests for changes"
    runs-on: ubuntu-20.04
    container:
      image: registry.fedoraproject.org/fedora:35

    steps:
      - name: Install build dependencies
        run: dnf -y install krb5-devel gcc git-core go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Generate manifests (PR HEAD)
        run: go run ./cmd/gen-manifests --output /manifests/PR

      - name: Checkout main
        run: git checkout main

      - name: Generate manifests (main)
        run: go run ./cmd/gen-manifests --output /manifests/main

      - name: diff
        run: diff -r /manifests/main /manifests/PR
