name: Manifests

# Detect if the PR introduced changes to image definitions / manifests and post
# a comment on the PR

# NOTE: Restricting branches prevents jobs from being doubled since a push to a
# pull request triggers two events.
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  check-manifests:
    name: "Check manifests for changes"
    runs-on: ubuntu-20.04
    container:
      image: registry.fedoraproject.org/fedora:35

    steps:
      - name: Install build dependencies
        run: dnf -y install krb5-devel gcc git-core go

      - name: Check out PR HEAD
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Generate manifests (PR HEAD)
        run: go run ./cmd/gen-manifests --output /manifests/PR --workers 120

      - name: Check out main
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Generate manifests (main)
        run: go run ./cmd/gen-manifests --output /manifests/main --workers 120

      - name: diff
        id: mdiff
        run: changes=$(diff -qr /manifests/main /manifests/PR)

      - name: Manifest changes detected
        env:
          URL: ${{ github.event.pull_request.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ failure() && steps.mdiff.conclusion == 'failure' }}
        run: |
          curl \
            -X POST \
            $URL \
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --data '{ "body": "Manifest changes detected" }'
